apisix:
  node_listen: 9080
  enable_admin: true
  enable_admin_cors: true
  enable_dev_mode: false
  enable_reuseport: true
  
  allow_admin:
    - 0.0.0.0/0

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  
  admin:
    admin_key:
      - name: "admin"
        key: admin-key-dev
        role: admin

  etcd:
    host:
      - "http://gemeente_etcd:2379"
    prefix: "/apisix"
    timeout: 30
    
nginx_config:
  error_log_level: warn
